config/routes.rb
Rails.application.routes.draw do
  
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :movies do
    collection do
      get 'search'
    end
    resources :reviews, except: [:show, :index]  
  end
  root 'movies#index'
  devise_for :users 

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/movie.rb
class Movie < ActiveRecord::Base
	searchkick
	belongs_to :user
	has_many :reviews
	has_attached_file :image, styles: { medium: "400x600" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
end

app/models/review.rb
class Review < ActiveRecord::Base
	belongs_to :user
	belongs_to :movie
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :movies
  has_many :reviews,dependent: :destroy       
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  before_action :set_movie, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]
  def search
    if params[:search].present?
      @movies=Movie.search(params[:search])
    else
      @movies=Movie.all
    end
  end
  # GET /movies
  # GET /movies.json
  def index
    @movies = Movie.all
  end

  # GET /movies/1
  # GET /movies/1.json
  def show
    @reviews =Review.where(movie_id: @movie.id).order("created_at DESC")
  end

  # GET /movies/new
  def new
    @movie = current_user.movies.build
  end

  # GET /movies/1/edit
  def edit
  end

  # POST /movies
  # POST /movies.json
  def create
    @movie = current_user.movies.build(movie_params)

    respond_to do |format|
      if @movie.save
        format.html { redirect_to @movie, notice: 'Movie was successfully created.' }
        format.json { render :show, status: :created, location: @movie }
      else
        format.html { render :new }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /movies/1
  # PATCH/PUT /movies/1.json
  def update
    respond_to do |format|
      if @movie.update(movie_params)
        format.html { redirect_to @movie, notice: 'Movie was successfully updated.' }
        format.json { render :show, status: :ok, location: @movie }
      else
        format.html { render :edit }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /movies/1
  # DELETE /movies/1.json
  def destroy
    @movie.destroy
    respond_to do |format|
      format.html { redirect_to movies_url, notice: 'Movie was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_movie
      @movie = Movie.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def movie_params
      params.require(:movie).permit(:title, :description, :duration, :image)
    end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_review, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  before_action :set_movie


  def new
    @review = Review.new
    
  end

  def edit
  end

  def create
    @review = Review.new(review_params)
    @review.user_id=current_user.id
    @review.movie_id=@movie.id
    @review.save
    redirect_to movie_path(@review.movie_id)
  end

  def update
    @review.update(review_params)
    
  end

  def destroy
    @review.destroy
    
  end

  private
    def set_review
      @review = Review.find(params[:id])
    end
    def set_movie
      @movie = Movie.find(params[:movie_id])
    end
    def review_params
      params.require(:review).permit(:rating, :comment)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Movie Reviews", root_path, class: "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <% if user_signed_in? %>
          <li><%= link_to "New Movie", new_movie_path, class: "active" %></li>
          <li><%= link_to "Account", edit_user_registration_path %></li>
          <li><%= link_to "sign out", destroy_user_session_path,method: :delete %></li>
        <% else %>
          <li><%= link_to "Sign Up", new_user_registration_path, class: "active" %></li>
          <li><%= link_to "Sign In", new_user_session_path, class: "active" %></li>
        <% end %>
      </ul>
      <%= form_tag search_movies_path, method: :get, class: "navbar-form navbar-right", role: "search" do %>
        <p>
          <%= text_field_tag :search, params[:search], class: "form-control" %>
          <%= submit_tag "Search", name: nil, class: "btn btn-default" %>
        </p>
      <% end %>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MovieReview</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render 'layouts/header' %>
<% flash.each do |name,msg| %>
<%= content_tag(:div, msg,class: "alert alert-info") %>
<% end %>
<%= yield %>

</body>
</html>

app/views/movies/_form.html.erb
<div class="col-md-6 col-md-offset-2">
  <div class="row">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h2>New Movie</h2>
      </div>

      <div class="panel-body">
<%= form_for @movie,html: {multipart: true} do |f| %>
  <% if @movie.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@movie.errors.count, "error") %> prohibited this movie from being saved:</h2>

      <ul>
      <% @movie.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<div class="form-inputs">
  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title , class: "form-control"%>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description , class: "form-control"%>
  </div>
  <div class="field">
    <%= f.label :duration %><br>
    <%= f.text_field :duration , class: "form-control"%>
  </div>
  <div class="field">
    <%= f.label :image %><br>
    <%= f.file_field :image %><br>
  </div>
  </div>
  <div class="actions">
    <%= f.submit "Add Movie",class: "btn btn-info" %>
  </div>
<% end %>
</div>
    </div>
  </div>
</div>

app/views/movies/edit.html.erb
<h1>Editing movie</h1>

<%= render 'form' %>

<%= link_to 'Show', @movie %> |
<%= link_to 'Back', movies_path %>

app/views/movies/index.html.erb
<div class="row">
<div class="container">
  <% @movies.each do |movie| %>
  <div class="col-sm-6 col-md-3">
  <div class="thumbnail">
    <%= link_to (image_tag movie.image.url(:medium), class:'image'), movie %>
    </div>
    </div>
    <%end %>
    </div>
</div>

app/views/movies/new.html.erb
<%= render 'form' %>

app/views/movies/search.html.erb
<div class="row">
<div class="container">
  <% @movies.each do |movie| %>
  <div class="col-sm-6 col-md-3">
  <div class="thumbnail">
    <%= link_to (image_tag movie.image.url(:medium), class:'image'), movie %>
    </div>
    </div>
    <%end %>
    </div>
</div>

app/views/movies/show.html.erb
<div class="container">
<div class="panel panel-default">
	<div class="panel-body">
	<div class="row">
	<div class="col-md-4">
	<%= image_tag @movie.image.url(:medium) %>
	<div class="table-responsive">
	<table class="table">
	<tbody>
		<tr>
		<td><strong>Title:</strong></td>
		<td><%=@movie.title%></td>
		</tr>
		<tr>
		<td><strong>Description:</strong></td>
		<td><%=@movie.description%></td>
		</tr>
		<tr>
		<td><strong>Duration:</strong></td>
		<td><%=@movie.duration%></td>
		</tr>
	</tbody>
	</table>
	<%= link_to 'write a review', new_movie_review_path(@movie) ,class: "btn btn-default"%>
	</div>
	</div>
	<div class="col-md-7 col-md-offset-1">
	<h1 class="review_title"><%= @movie.title %></h1>
	<p><%= @movie.description %> </p>
	<% if @reviews.blank? %>
	<h3>no reviews yet,be the first to add one</h3>
	<%= link_to "write review",new_movie_review_path(@movie),class: "btn btn-default" %>
	<%else%>
	<% @reviews.each do |r| %>
	<div class="reviews">
	<p><%= r.rating %></p>
	<p><%= r.comment %></p>
	</div>
	<%end%>
	<% end %>
	</div>
	</div>
	</div>
</div>
<center>
<%= link_to 'Edit', edit_movie_path(@movie),class: "btn btn-default" %>
<%= link_to 'Back', movies_path,class: "btn btn-default" %>
</center>
</div>

app/views/reviews/_form.html.erb
<div class="col-md-4 col-md-offset-2">
  <div class="row">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h2>Review</h2>
      </div>

      <div class="panel-body">
<%= form_for([ @movie,@review]) do |f| %>
  <% if @review.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@review.errors.count, "error") %> prohibited this review from being saved:</h2>

      <ul>
      <% @review.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :rating %><br>
    <%= f.number_field :rating ,class: "form-control"%>
  </div>
  <div class="field">
    <%= f.label :comment %><br>
    <%= f.text_area :comment ,class: "form-control"%>
  </div><br>
  <div class="actions">
    <%= f.submit "submit",class: "btn btn-info" %>
  </div>
<% end %>
<hr>
<%= link_to 'Back', @movie ,class: "btn btn-info"%>
</div>
    </div>
  </div>
</div>

app/views/reviews/edit.html.erb
<h1>Editing review</h1>

<%= render 'form' %>

<%= link_to 'Back', @movie %>

app/views/reviews/new.html.erb
<%= render 'form' %>